### PR TITLE
MM-27147 - Added entry for Cloud api

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Added entry for initial Cloud api endpoints that include:

- GET `/cloud/products`
- POST `/cloud/payment/`
- POST /cloud/payment/confirm

#### Related PRs
Server: https://github.com/mattermost/mattermost-server/pull/15428

#### Ticket Link
[MM-27147](https://mattermost.atlassian.net/browse/MM-27147)

### CODE REVIEW

**Comment by jwilander** [comment]
I wonder if we should leave these out of the API docs and mark them in code with comments saying they're "internal and subject to change". Thoughts?

**Comment by marianunez** [comment]
Agreed these do not make sense in the full api documentation given that they are not intended to be used outside of cloud but the build is not happy about that here: https://github.com/mattermost/mattermost-server/pull/15428

How do I get them to skip this validation?

**Comment by ethervoid** [comment]
I had this conversation when I made the /login/cws endpoint, in the server channel and all of them prefer to have all the endpoints documented and public.

**Review by ethervoid — APPROVED** [review]
LGTM

**Comment by jwilander** [comment]
I'm fine with having them documented and public. @marianunez maybe just add a line in each endpoint noting that they're meant for internal use and are subject to change

**Comment by marianunez** [comment]
> I'm fine with having them documented and public. @marianunez maybe just add a line in each endpoint noting that they're meant for internal use and are subject to change

Note added.

**Review by jwilander — APPROVED** [review]

**Pull request merged**
