### PR TITLE
Revert "add dnd_end_time in requestBody of updateStatus (#629)"

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
This reverts commit 3d898faea72c448e89d088a26e1b870722f9d7d9.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/15640

### CODE REVIEW

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
@lieut-data This one also needs a cherry-pick to ``cloud``.

**Comment by amyblais** [comment]
@lieut-data Would you be able to help cherry-pick this one too?

**Comment by lieut-data** [comment]
Done! https://github.com/mattermost/mattermost-api-reference/commit/c586a804a0da641f12e580cba01b6e0f60ae3058

**Pull request merged**
