### PR TITLE
MM-34437 Added API docs for new prev trial license fetching API

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary

Added API doc for fetching last trial license

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34437

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Comment by hanzei** [comment]
@harshilsharma63 Can this be merged?

**Comment by harshilsharma63** [comment]
@BenCookie95 we can if merging it won't get reflected in the API docs. @amyblais maybe you can confirm that as I don't have much idea about how API docs are released?

**Comment by amyblais** [comment]
I'll add Do Not Merge label as the corresponding webapp and server PRs are still open.

**Comment by BenCookie95** [comment]
> @BenCookie95 we can if merging it won't get reflected in the API docs. @amyblais maybe you can confirm that as I don't have much idea about how API docs are released?

@harshilsharma63 I think you meant to tag @hanzei

**Comment by harshilsharma63** [comment]
@amyblais this can be merged now after merging webapp and server PRs.

**Pull request merged**
