### PR TITLE
Add Playbook APIs to Mattermost API docs

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary
This PR integrates the API spec for Playbooks into the Mattermost API docs. The Playbooks OpenAPI spec is downloaded from GitHub at build time, and then it is parsed, split up, and combined with the existing API specs in YAML files.

At the time of this PR posting, OpenAPI service tags are not present in the Playbooks API specs. Substitute tags are provided in the `playbooks/tags.yaml` file until tags are added to the spec.

### CODE REVIEW

**Comment by itao** [comment]
Is there a way to browse the API docs pages that are outputted at the end of this?

**Comment by neflyte** [comment]
It doesn't look like the preview environment has been set up for this repo. :(

**Comment by lieut-data** [comment]
@cwarnermm / @justinegeffen, do you know how to "preview" the changes in flight here?

**Comment by cwarnermm** [comment]
@lieut-data - Unfortunately, I don't believe we have a generated preview option available yet for this repository like we do for the developer documentation or product documentation repositories.

You may need to pull this fork down to a local dev environment instead.

**Review by lieut-data — APPROVED** [review]
I don't feel I have enough context into the upgraded dependencies to review those, but the code makes sense. If we eventually extend this to include Boards and other APIs, we may want a more holistic approach to stitching things together, but this looks to work well. Thanks @neflyte!

**Comment by cwarnermm** [comment]
@neflyte - Can you provide some context around the dependency updates included in this PR. This is useful context for the Engineering team.

**Review by crspeller — APPROVED** [review]

**Comment by neflyte** [comment]
The `sync-fetch` and `yaml` dependencies were added so the Playbooks OpneAPI specs could be retrieved on demand and integrated into the existing MM OpenAPI specs.

I cannot find any changelogs for `redoc-cli`; I have no idea what has changed, however I can rever back to the previous `^0.13.16` version string; please let me know.

**Comment by lieut-data** [comment]
@neflyte, no objections to upgrading -- thanks for adding clarity! @cwarnermm, any final steps on this before merging?

**Comment by cwarnermm** [comment]
@lieut-data - Nothing else is needed; feel free to merge when convenient!

**Comment by lieut-data** [comment]
Awesome, thank you again @neflyte!

**Pull request merged**
