### PR TITLE
Post Reminders API Docs

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- API documentation for post reminders
 
#### Ticket Link

- N/A

### CODE REVIEW

**Comment by cwarnermm** [comment]
@ashishbhate - Is the post reminders feature intended to have a client-facing interface as well? If it does, then we may want to hold off publishing the API updates until this feature is available in-product. @agnivade - Thoughts?

**Comment by agnivade** [comment]
I am 0/5, but the context here is that the server side PR is merged, but client side work is still going on. So technically speaking you can use the API using a CLI client. But obviously no client side interface is done yet.

No worries with holding off if you think so.

**Comment by ashishbhate** [comment]
@cwarnermm Agniva summarised the context perfectly. I'll defer to whatever you think is best as well :)

**Comment by cwarnermm** [comment]
Thank you both! I agree with @agnivade that since the server-side work is complete, and it's possible for customers to start using it, it makes sense to publish now rather than to wait!

Please note that we're currently experiencing issues with the API Reference site. Investigation is ongoing, but this content _may_ not be accessible until issues on the site have been addressed.

**Review by cwarnermm — APPROVED** [review]
Thank you, @ashishbhate!

**Review by agnivade — APPROVED** [review]

**Pull request merged**
