### PR TITLE
Docs for APIv4: GET /files/{file_id}/info

### PR DESCRIPTION
**Pull request by saturninoabril**
This is documentation for APIv4: GET /files/{file_id}/info

### CODE REVIEW

**Comment by jwilander** [comment]
@saturninoabril can you rebase this and then I can merge?

**Comment by saturninoabril** [comment]
I'll just wait for the other [files PR #125](https://github.com/mattermost/mattermost-api-reference/pull/125) to get merge before rebasing this.

**Comment by jwilander** [comment]
Ready for rebase

**Comment by saturninoabril** [comment]
done rebase. thanks

**Pull request merged**
