### PR TITLE
PLT-6083: API to get users not in a team.

### PR DESCRIPTION
**Pull request by grundleborg**
API to get users not in a team.

https://mattermost.atlassian.net/browse/PLT-6083

### CODE REVIEW

**Comment by jwilander** [comment]
@hmhealey just added this ability for v4 in #172 and is going to hit that endpoint in the webapp using a custom driver function so he can use it in 3.8. Wondering if that can work for what you need as well?

**Comment by hmhealey** [comment]
@jwilander Mine is different. It's an API for users not in any team. @grundleborg could do a similar method of just hooking into an APIv4 call though

**Comment by jwilander** [comment]
Ah right, this is for not in a specific team not for users without any team.

Yes, preferably we just add this to the v4 endpoint instead of having to add a new v3 endpoint

**Comment by hmhealey** [comment]
@grundleborg Also, if you end up just writing the API v4 version and calling it with the v3 client, make sure you remember that the v4 API returns a list of users instead of a map. It took me a fair bit of debugging to realize that I was merging an array and a map in the user store which caused all sorts of problems

**Comment by grundleborg** [comment]
@hmhealey @jwilander updated. How's this look?

**Pull request merged**
