### PR TITLE
Custom status expiry

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary
Modified documentation for custom status APIs adding expiry support

#### Related pull requests
https://github.com/mattermost/mattermost-server/pull/17570

### CODE REVIEW

**Comment by manojmalik20** [comment]
@esethna Could you please add some reviewers here?

**Comment by hmhealey** [comment]
Looks good assuming we don't change how we pass the expiry as per https://github.com/mattermost/mattermost-server/pull/17570#discussion_r626513565

**Review by jespino — APPROVED** [review]
LGTM

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
We're waiting on the corresponding webapp and server PRs to merge this.

**Comment by amyblais** [comment]
@jespino @hmhealey Can you help cherry-pick to the ``cloud`` branch?

**Comment by amyblais** [comment]
@jespino @hmhealey Can this be cherry-picked to the ``cloud`` branch?

**Pull request merged**
