### PR TITLE
Adding operationIds to API documentation

### PR DESCRIPTION
**Pull request by gmerz**
#### Summary

+ adds operationIds to the API endpoints. The issue of missing Ids was already discussed in #88

### CODE REVIEW

**Comment by gmerz** [comment]
Hi @jwilander. Is there any kind of help I can offer, or any further information you would require to move this forward? I would be happy to help.

**Comment by jasonblais** [comment]
@jwilander I assume this would go to someone on the messaging vertical to review?

Thanks @gmerz for the contribution, really appreciate it!

**Comment by jwilander** [comment]
@gmerz apologies for the slow response here. Taking a look now

**Review by jwilander — APPROVED** [review]
LGTM - thanks @gmerz !

**Review by crspeller — APPROVED** [review]

**Pull request merged**
