### PR TITLE
documentation: 'D' direct channel for "channel a update"

### PR DESCRIPTION
**Pull request by Ashid6**
description for "direct channel" should also come for "update a channel"

### CODE REVIEW

**Comment by ABresting** [comment]
Hi All, I am a GSoD'19 applicant. This is a minor fix but completes the channels.yml issue #429

**Comment by Ashid6** [comment]
Hi All, I am a GSoD'19 applicant. This is a minor fix but completes the channels.yml issue #429

**Comment by jwilander** [comment]
Hi @Ashid6, `D` is not actually a valid input for this API. To fix the linked ticket I think what we need to do is update the responses to any of the channel endpoints that return channels with a description on the `type` field explaining what the different values can be. Does that make sense?

**Comment by Ashid6** [comment]
@jwilander yeah that makes sense. To update the responses I think we can change the definitions.yaml file  at https://github.com/mattermost/mattermost-api-reference/blob/master/v4/source/definitions.yaml#L141
here should we add "description:" with the types of the channel i.e. "O" and "P"

But the problem is #definitions/channel is used by many different types of requests, where not necessary  "O" and "P" types are used. either make inline change just every type of request or make new keys in definitions.yaml What do you think?

**Comment by jwilander** [comment]
Sorry for the late response @Ashid6 

I'd suggest trying new definitions first. If they don't end up being very reusable then I think it would make sense to move to inline changes for each request

**Comment by jasonblais** [comment]
Hey @Ashid6, let us know if you have any questions about the above? Happy to help :)

**Comment by hanzei** [comment]
Closing this PR due to inactivity. Still, thanks for the contribution, @Ashid6! Let me know, if you still want to work on this.

**Pull request closed without merging**
