### PR TITLE
MM-9779: Add api documentation changes for avoid re-join on invitations feature

### PR DESCRIPTION
**Pull request by jespino**
It is the documentation for the Ticket [MM-9779](https://mattermost.atlassian.net/browse/MM-9779) in the PR mattermost/mattermost-server#8604

### CODE REVIEW

**Comment by jespino** [comment]
Rebased. Still failing because every single api-documentation PR is failing.

**Comment by jespino** [comment]
It doesn't build, but it doesn't build in master neither

**Comment by saturninoabril** [comment]
I'm seeing below error on master which is caused by the most recent commit. May need to fix separately but might be good to include as well with your PR :)
```
Building mattermost openapi yaml for v4
Error parsing /Users/saturnino/go/src/github.com/mattermost/mattermost-api-reference/v4/html/static/mattermost-openapi-v4.yaml 
bad indentation of a mapping entry at line 3094, column 3:
      /channels:
      ^
```

**Comment by jespino** [comment]
I already make a PR solving the problem

**Comment by cpanato** [comment]
@saturninoabril this is current in master. I'm fixing the jenkins pipeline now. i think in a few we will have the jenkins build again. sorry for the delay

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
09328741092837401928374

**Comment by cpanato** [comment]
@jespino can you please rebase?

**Comment by cpanato** [comment]
@crspeller no more build issues 😹

**Comment by jespino** [comment]
Rebased :)

**Pull request merged**
