### PR TITLE
MM-14294: update API to reflect hard-coded SAML certificate names

### PR DESCRIPTION
**Pull request by lieut-data**
This change complements https://github.com/mattermost/mattermost-server/pull/10341.

### CODE REVIEW

**Comment by hanzei** [comment]
Hey @lieut-data,

Is this ready to merge?

**Comment by lieut-data** [comment]
Hey @hanzei! It's ready in terms of the needed changes, but won't go into until we release 5.10. Might need to tweak the rules for this repository or just anticipate the lifecyle and freeze upfront.

**Comment by hanzei** [comment]
Let's use the same process as the docs repo and add `Merge On Hold`.

**Comment by hanzei** [comment]
@lieut-data Can this be merged?

**Pull request merged**
